import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Page from "@/app/sign-in/[[...sign-in]]/page";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { SidebarProvider } from "@/context/SidebarContext";
import { ChatProvider } from "@/context/ChatContext";
import ChatModal from "@/components/ui/ChatModal";
import GlobalHelpModal from "@/components/ui/GlobalHelpModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EYIDE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        
        <body className="bg-[#0E1111]">
            <SignedOut>
              <Page />
            </SignedOut>
            <SignedIn>            
              <ThemeProvider>
                <SidebarProvider>
                  <ChatProvider>
                    <main>{children}</main>
                    <ChatModal />
                    <GlobalHelpModal />
                  </ChatProvider>
                </SidebarProvider>
              </ThemeProvider>
            </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}